### ISSUE TITLE
Добавить возможность передавать признак и опции блокировки прокрутки страницы в компонент PersonModal

### ISSUE THREAD

**Issue by dmitry-shishkin** [sima-land/moleculas#10]

**Comment by barabaiiika** [comment]
Необходимо добавить возможность передавать признак и опции блокировки прокрутки страницы в компонент PersonModal, которые будут применяться к компоненту Modal https://github.com/sima-land/moleculas/blob/510bc4a5ee695955df5111952e96263dc2b9877b/src/desktop/components/person-modal/index.tsx#L63
