### ISSUE TITLE
ProductInfo.Parts: Type '{ children: Element; }' has no properties in common with type

### ISSUE THREAD

**Issue by korniux** [sima-land/moleculas#134]
https://github.com/sima-land/moleculas/blob/a30792fe4a00d197fd44a99252a3a79dacb6412f/src/common/components/product-info/parts.tsx#L235

Typecheck ругается на `React.FC<{}>` так как в последних версиях требуется декларировать тип свойств даже если там только `children`, к примеру `React.FC<React.PropsWithChildren>`

**Comment by krutoo** [comment]
исправим когда введем поддержку React 18, сейчас поддерживается только 16-17
