### ISSUE TITLE
InteractiveImage: Поправить размер точек

### ISSUE THREAD

**Issue by robertsh8** [sima-land/moleculas#135]
В гайдах по интерактивному баннеру уточнили [требования по точкам](https://www.figma.com/file/X6W8v6PPIjytxCCd9Po5wg/Banners?node-id=3249%3A1617&t=t6BwFrjS0nsx4fs7-4). Они должны быть одинакового размера на всех разрешениях.

**Comment by krutoo** [comment]
Компонент позволяет задать размер точек вручную, этот функционал подойдет для решения данной задачи?

**Comment by robertsh8** [comment]
Да, подходит. Закрываю тикет, спасибо.
