### ISSUE TITLE
Обновить компонент ProductCard

### ISSUE THREAD

**Issue by GrigoriyYakimov** [sima-land/moleculas#256]
#### Ситуация

Дизайн-гайды компонента ProductInfo обновились

#### Необходимо

- Убрать из библиотеки возможность выводить всплывающие карточки при наведении на ProductInfo
- Добавить возможность выводить несколько картинок с перелистыванием в ProductInfo

**Comment by krutoo** [comment]
выкатил релиз 16.0.0-alpha.23 с обновлениями
