### ISSUE TITLE
ProductInfo: доработать в соответствии с новыми дизайн-гайдами

### ISSUE THREAD

**Issue by MaratKhaid** [sima-land/moleculas#279]
**Ситуация**

Обновлён гайд карточки товара ProductInfo, теперь пагинация фото появляется только при наведении на карточку, а у товаров 18+ фото переключать нельзя

**Необходимо**

•‎ Пагинацию фото выводить только при ховере на всю область карточки.
•‎ У товара 18+ отключить возможность переключения фото и не отображать пагинацию

**Comment by krutoo** [comment]
также в рамках задачи придумать как вернуть возможность задать alt
